### ISSUE TITLE
Problem starting up docker container in isolation

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/docker#12]
We seemed to have broken something with dotCMS container.  I was running some regression test and just starting up dotCMS container all by itself with this command:
```docker run -itp 8080:8080 dotcms/dotcms:5.1.6-osalpha```

On startup it hangs for a very long time after this line in the log:
```Building Cache : pagemultitreesworking, size:1000,Concurrency:32```

See log file summary, threaddump, and full log file here:  https://gist.github.com/brentgriffin/0d5e7638dc015d14695904baa4219dd6

**Comment by brentgriffin** [comment]
I have seen it hang for over 40 minutes here or as little as 4 minutes but almost always hangs

**Comment by wezell** [comment]
I just ran the docker image twice
```
docker pull dotcms/dotcms:latest
docker run  -itp 8080:8080 dotcms/dotcms:latest
```
both times it came up fast and worked.

Next I built against our Dockerfile in docker/master
```
docker build --pull --no-cache --build-arg BUILD_FROM=COMMIT --build-arg BUILD_ID=5.1.6 -t test .
```
and it worked again

**Comment by SantoshTirukkovilour** [comment]
I ran docker image using below command several times

docker run -itp 8080:8080 dotcms/dotcms:5.1.6-osalpha

always it start up fast and working fine, didn't find any issues.

Also I built dotcms image in docker/openshiftchanges

docker build --pull --no-cache --build-arg BUILD_FROM=RELEASE --build-arg BUILD_ID=5.1.6 -t dotcms-test .

It's also worked without any issues.

See full log file here:
https://gist.github.com/SantoshTirukkovilour/e44ad102825455ab3924e1f36a81efba

**Comment by brentgriffin** [comment]
Will - you are using a different branch - we have been making changes to the images so that they will work properly in openshift.  You are using a different branch and a different image tag.

**Comment by brentgriffin** [comment]
@SantoshTirukkovilour - please verify your dotcms docker image id - if you are running the one from dockerhub you should have an image id of `b6c580381b7b`

```
~$ docker image ls
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
dotcms/dotcms                      5.1.6-osalpha       b6c580381b7b        16 hours ago        1.08GB
```

I am concerned that you may be running the image built locally by openshift and not the image in dockerhub.

**Comment by SantoshTirukkovilour** [comment]
@brentgriffin  - Just verified I am also using same image id, please find below details.
```
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
dotcms/dotcms           5.1.6-osalpha       b6c580381b7b        16 hours ago        1.08GB
```

**Comment by brentgriffin** [comment]
Not a docker specific issue.  It was an environment issue.  Both servers were AWS Ubuntu servers.  The issue was a lack of entropy - couple different ways to address but chose this solution:  https://www.howtoforge.com/helping-the-random-number-generator-to-gain-enough-entropy-with-rng-tools-debian-lenny

Issue resolved both for running dotCMS containerized and non-containerized.
