### ISSUE TITLE
ES Configuration Variables Ignored in dotCMS version 5.3.5 docker image

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/docker#38]
Bottom line, prior to 5.3.5 we used PROVIDER_ELASTICSEARCH_PROTOCOL, PROVIDER_ELASTICSEARCH_DNSNAMES, and PROVIDER_ELASTICSEARCH_PORT_HTTP to set ES client settings in the docker image.

With 5.3.5 these variables exist but are effectively ignored and PROVIDER_ELASTICSEARCH_ENDPOINTS must be used instead.

### Recommendations:

- Remove these ignored variables - don't see a real reason to have multiple ways to set the same settings.  Just leads to possible confusion and bugs like this one.

- Alternatively fix the [dotcms-config-cluster.properties](https://github.com/dotCMS/docker/blob/master/images/dotcms/ROOT/srv/templates/dotcms/CONF/dotcms-config-cluster.properties#L29) so that it only sets ES_ENDPOINTS if PROVIDER_ELASTICSEARCH_ENDPOINTS has a value. 

### Details
Problem was introduced [here](https://github.com/dotCMS/core/blob/v5.3.5/dotCMS/src/main/java/com/dotcms/content/elasticsearch/util/DotRestHighLevelClientProvider.java#L190-L207):  https://github.com/dotCMS/core/issues/18870
As you can see if ES_ENDPOINTS here is set, getDefaultEndpoint is never called which basically causes the ES_HOSTNAME, ES_PROTOCOL, and ES_PORT to be ignored.   As you can see [here](https://github.com/dotCMS/docker/blob/master/images/dotcms/ROOT/srv/templates/dotcms/CONF/dotcms-config-cluster.properties#L29), ES_ENDPOINTS is always set in the Docker container.

### Documentation
If the previous settings are going to be ignored or removed, should be documented in the documentation.  I saw the example configurations changed but I did not see any documentation that indicated that the docker config for 5.3.x would no longer work with 5.3.5.

**Comment by nollymar** [comment]
Fixed. Now, `ES_HOSTNAME`, `ES_PROTOCOL` and `ES_PORT` are not needed anymore. All the configuration should be set using `PROVIDER_ELASTICSEARCH_ENDPOINTS `
