### ISSUE TITLE
Content import and exports limited to 10,000?

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/docker#8]
Customer indicated that exports and imports from content search screen seem to be limited to 10,000 - is this specific to dockerized version or an issue with 5.x?

Customer had a valid license file applied to the the server at the time.

**Comment by wezell** [comment]
That is a hard limit on returning contents.

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L226

**Comment by brentgriffin** [comment]
That matches the fact that I was able to reproduce this issue without docker involved.
